version: '3.8'

services:
  spring-app:
    build:
      context: ../springbootapp
    ports:
      - "8081:8081"
    container_name: springbootapp
    healthcheck:
      test: ["CMD-SHELL", exit 0"]

  pytest-tests:
    build:
      context: ../pytestproject
    depends_on:
      spring-app:
        condition: service_healthy
    container_name: pytest-tests
