version: '3.8'

networks:
  upmonth-dev-tests:
    driver: bridge

services:

  mongodb:
    image: mongo
    container_name: mongodb
    volumes: 
      - mongodb_data:/data/db
    ports: 
      - 27017:27017
    restart: always
    networks:
      - upmonth-dev-tests

  upmanalytics:
    build:
      context: ../upmonth-analytics
      dockerfile: ./dockerFiles/Dockerfile-dev
      args:
        ARG_VERSION: ${UPM_ANALYTICS_VERSION}
    container_name: upmanalytics
    ports:
      - 9966:9966
    depends_on:
      - mongodb
    restart: always
    networks:
      - upmonth-dev-tests

  upmonth-database:
    image: mysql:5.7
    container_name: testupmonthdb
    ports:
      - "3308:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=upmonth
      - MYSQL_USER=upmonth
      - MYSQL_PASSWORD=upmonth
      - MYSQL_DATABASE=testupmonthdb
    volumes:
      - upmonth-database-data:/var/lib/mysql
      - ./mysql-custom.cnf:/etc/mysql/conf.d/custom.cnf
    networks:
      upmonth-dev-tests:
        aliases:
          - upmonthdb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pupmonth"]
      interval: 5s
      timeout: 5s
      retries: 30
    command: --default-authentication-plugin=mysql_native_password

  db-init:
    image: mysql:5.7
    depends_on:
      upmonth-database:
        condition: service_healthy
    networks:
      - upmonth-dev-tests
    environment:
      MYSQL_ROOT_PASSWORD: upmonth
    entrypoint:
      - sh
      - -c
      - |
        mysql -h upmonthdb -uroot -p"$MYSQL_ROOT_PASSWORD" -e "CREATE DATABASE IF NOT EXISTS upmonthdb CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"


  spring-app:
    build:
      context: ../springbootapp
    ports:
      - "8081:8081"
    container_name: springbootapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://upmonthdb:3306/upmonthdb?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&connectTimeout=30000
      SPRING_DATASOURCE_USERNAME: upmonth
      SPRING_DATASOURCE_PASSWORD: upmonth
    depends_on:
      - db-init
    networks:
      - upmonth-dev-tests
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]
      interval: 10s
      timeout: 5s
      retries: 10

  pytest-tests:
    build:
      context: ../pytestproject
    depends_on:
      spring-app:
        condition: service_healthy
    container_name: pytest-tests
    networks:
      - upmonth-dev-tests

volumes:
  upmonth-database-data: